export const sitemapEntries = [
  { path: '/', sources: ['src/pages/index.astro'], fallbackLastmod: '2026-07-16' },
  { path: '/sr/', sources: ['src/pages/sr.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/about/', sources: ['src/components/AboutPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/about/', sources: ['src/components/AboutPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-chatbot/', sources: ['src/components/AIChatbotPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-chatbot/', sources: ['src/components/AIChatbotPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-automation/', sources: ['src/components/AIAutomationPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-automatizacije/', sources: ['src/components/AIAutomationPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/web-development/', sources: ['src/components/WebDevelopmentPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/izrada-sajtova/', sources: ['src/components/WebDevelopmentPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-phone-agent/', sources: ['src/components/AIPhoneAgentPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-telefonski-agent/', sources: ['src/components/AIPhoneAgentPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/custom-ai-systems/', sources: ['src/components/CustomAISystemsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/prilagodjeni-ai-sistemi/', sources: ['src/components/CustomAISystemsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-dentists/', sources: ['src/components/DentalPracticesPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-stomatologe/', sources: ['src/components/DentalPracticesPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-travel-agencies/', sources: ['src/components/TravelAgenciesPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-turisticke-agencije/', sources: ['src/components/TravelAgenciesPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-law-firms/', sources: ['src/components/LawFirmsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-advokatske-kancelarije/', sources: ['src/components/LawFirmsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-hotels/', sources: ['src/components/HotelsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-hotele/', sources: ['src/components/HotelsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-instagram-shops/', sources: ['src/components/InstagramShopsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-instagram-prodavnice/', sources: ['src/components/InstagramShopsPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-real-estate/', sources: ['src/components/RealEstatePage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-nekretnine/', sources: ['src/components/RealEstatePage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-service-businesses/', sources: ['src/components/ServiceBusinessesPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-servise/', sources: ['src/components/ServiceBusinessesPage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/ai-for-ecommerce/', sources: ['src/components/EcommercePage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/ai-za-ecommerce/', sources: ['src/components/EcommercePage.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/privacy/', sources: ['src/pages/privacy.astro', 'src/components/LegalDocument.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/privacy/', sources: ['src/pages/sr/privacy.astro', 'src/components/LegalDocument.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/terms/', sources: ['src/pages/terms.astro', 'src/components/LegalDocument.astro'], fallbackLastmod: '2026-07-20' },
  { path: '/sr/terms/', sources: ['src/pages/sr/terms.astro', 'src/components/LegalDocument.astro'], fallbackLastmod: '2026-07-20' }
];
